package com.github.dkwasniak.goldendiff.compare

import com.github.dkwasniak.goldendiff.variant.ExtraComparisonSources
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class FigmaImageSourceTest {

    @Test
    fun `figma variant registers figma comparison source`() {
        assertTrue(ExtraComparisonSources.all.any { it.id == "figma" && it is FigmaImageSource })
    }

    @Test
    fun `parses figma generated preview block before annotations`() {
        val previews = FigmaImageSource().parseFigmaPreviews(
            """
            // Generated by figma-compose-preview — do not edit; used for Roborazzi–Figma pixel comparison.
            // Figma source: https://www.figma.com/design/fileKey/File?node-id=1-2&m=dev
            @Preview(uiMode = Configuration.UI_MODE_NIGHT_YES, locale = "en", showSystemUi = false)
            @Composable
            fun PlanRouteScreenFigmaSelectedRouteDarkPreview() {
                PreviewSurface(ignorePadding = true) {
                }
            }
            """.trimIndent(),
        )

        assertEquals(
            listOf(
                FigmaPreview(
                    "PlanRouteScreenFigmaSelectedRouteDarkPreview",
                    "https://www.figma.com/design/fileKey/File?node-id=1-2&m=dev",
                ),
            ),
            previews,
        )
    }
}
