package com.github.dkwasniak.goldendiff.settings

import com.github.dkwasniak.goldendiff.match.MatchMode
import com.github.dkwasniak.goldendiff.match.MatchingDefaults
import com.github.dkwasniak.goldendiff.variant.ExtraComparisonSources
import com.intellij.openapi.components.PersistentStateComponent
import com.intellij.openapi.components.Service
import com.intellij.openapi.components.State
import com.intellij.openapi.components.Storage
import com.intellij.openapi.components.service
import com.intellij.openapi.project.Project
import com.intellij.util.xmlb.XmlSerializerUtil
import java.io.File

/**
 * Project-level persisted configuration. The screenshot directories are project specific, so the
 * user picks them per project (on first run, or later in Settings).
 */
@Service(Service.Level.PROJECT)
@State(
    name = "GoldenDiffSettings",
    storages = [Storage("goldenDiff.xml")]
)
class ScreenshotSettings : PersistentStateComponent<ScreenshotSettings.State> {

    class State {
        // Paths to directories that contain screenshot golden files. Relative paths are resolved
        // against the project base directory; absolute paths are kept supported for compatibility.
        var paths: MutableList<String> = ArrayList()
        // Paths to directories that contain screenshots generated by verification tests. Relative
        // paths are resolved against the project base directory.
        var generatedPaths: MutableList<String> = ArrayList()
        // Regex for selecting generated screenshots. First capture group maps to the golden basename.
        var generatedFileRegex: String = GoldenDiffDefaults.GENERATED_FILE_REGEX
        // Which matching mode is active. See MatchMode.
        var matchMode: String = MatchingDefaults.DEFAULT_MATCH_MODE.name
        // Regex applied to annotation names. Matching annotated functions become golden candidates.
        var annotatedFunctionRegex: String = MatchingDefaults.ANNOTATION_NAME_REGEX
        // Regex patterns for the file/class matching mode. Support {file_name} and {class_name}.
        var goldenFilePatterns: MutableList<String> = MatchingDefaults.DEFAULT_FILE_CLASS_PATTERNS.toMutableList()
        // File-name suffixes (before the extension) whose files are not goldens themselves and are
        // excluded from the golden list, e.g. Roborazzi's `_compare` / `_actual` artifacts.
        var excludedSuffixes: MutableList<String> = GoldenDiffDefaults.EXCLUDED_SUFFIXES.toMutableList()
        // When true, fully transparent padding around an image's content is trimmed before it is shown
        // (comparison view and list thumbnails). Off by default so images are shown exactly as stored.
        var trimTransparentPadding: Boolean = false
    }

    private var state = State()

    override fun getState(): State = state

    override fun loadState(loaded: State) {
        XmlSerializerUtil.copyBean(loaded, state)
    }

    // Called only when there is no persisted config yet (first run). First-run directory defaults are
    // contributed by dependent plugins through the comparison-source extension point (the internal
    // Figma plugin supplies them). With no such plugin installed, the public plugin stays empty.
    override fun noStateLoaded() {
        val defaults = ExtraComparisonSources.all.firstNotNullOfOrNull { it.firstRunDefaults() } ?: return
        defaults.goldenPaths.takeIf { it.isNotEmpty() }?.let { state.paths = it.toMutableList() }
        defaults.generatedPaths.takeIf { it.isNotEmpty() }?.let { state.generatedPaths = it.toMutableList() }
    }

    var paths: List<String>
        get() = state.paths.toList()
        set(value) {
            state.paths = value.toMutableList()
        }

    var generatedPaths: List<String>
        get() = state.generatedPaths.toList()
        set(value) {
            state.generatedPaths = value.toMutableList()
        }

    var generatedFileRegex: String
        get() = state.generatedFileRegex.ifBlank { GoldenDiffDefaults.GENERATED_FILE_REGEX }
        set(value) {
            state.generatedFileRegex = value.ifBlank { GoldenDiffDefaults.GENERATED_FILE_REGEX }
        }

    var excludedSuffixes: List<String>
        get() = state.excludedSuffixes.toList()
        set(value) {
            state.excludedSuffixes = value.toMutableList()
        }

    var trimTransparentPadding: Boolean
        get() = state.trimTransparentPadding
        set(value) {
            state.trimTransparentPadding = value
        }

    var matchMode: MatchMode
        get() = MatchMode.fromName(state.matchMode)
        set(value) {
            state.matchMode = value.name
        }

    var annotatedFunctionRegex: String
        get() = state.annotatedFunctionRegex.ifBlank { MatchingDefaults.ANNOTATION_NAME_REGEX }
        set(value) {
            state.annotatedFunctionRegex = value.ifBlank { MatchingDefaults.ANNOTATION_NAME_REGEX }
        }

    var goldenFilePatterns: List<String>
        get() = state.goldenFilePatterns.ifEmpty { MatchingDefaults.DEFAULT_FILE_CLASS_PATTERNS }.toList()
        set(value) {
            state.goldenFilePatterns = value.ifEmpty { MatchingDefaults.DEFAULT_FILE_CLASS_PATTERNS }.toMutableList()
        }

    val isConfigured: Boolean
        get() = state.paths.isNotEmpty()

    val hasGeneratedPaths: Boolean
        get() = state.generatedPaths.isNotEmpty()

    /**
     * Snapshot of the persisted state in the form the platform-independent core understands.
     *
     * The accessors above already substitute defaults for blank or empty values, which matters here:
     * `goldenDiff.xml` is a plain file a user can hand-edit into a state the UI would never produce.
     * Core code is handed values that are always usable.
     */
    fun toConfig(): GoldenDiffConfig = GoldenDiffConfig(
        goldenPaths = paths,
        generatedPaths = generatedPaths,
        generatedFileRegex = generatedFileRegex,
        matchMode = matchMode,
        annotatedFunctionRegex = annotatedFunctionRegex,
        goldenFilePatterns = goldenFilePatterns,
        excludedSuffixes = excludedSuffixes,
        trimTransparentPadding = trimTransparentPadding,
    )

    fun resolvedPaths(project: Project): List<File> =
        toConfig().resolvedGoldenPaths(project.rootDir())

    fun resolvedGeneratedPaths(project: Project): List<File> =
        toConfig().resolvedGeneratedPaths(project.rootDir())

    private fun Project.rootDir(): File? = basePath?.let(::File)

    companion object {
        fun getInstance(project: Project): ScreenshotSettings = project.service()
    }
}
